import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class Event {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
   int? id; 

  //The carbohydrates content of the meal
   String pranzo1;
   String pranzo2;
   String pranzo3;
   String pranzo4;

   String cena1;
   String cena2;
   String cena3;
   String cena4;   
   
   String snack;

   String colazione;
  
  //When the meal occured
   DateTime from;

  //Default constructor
  Event(this.id, this.pranzo1, this.pranzo2,this.pranzo3,this.pranzo4, this.cena1,this.cena2,this.cena3,this.cena4,this.snack,this.colazione,this.from,);
  
}//Meal