import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class Level{
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? id;

  //The max value the user want to be seated in a day
  double counter;

  double livello;

  double a;
  //Default constructor
  Level(this.id, this.counter,this.livello,this.a);
} //Sedentary 
