import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class Medal {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
   int? id; 

   int? medal1;
   int? medal2;
   int? medal3;
   int? medal4;
   int? medal5;

   int? medal6;
   int? medal7;
   int? medal8;
   int? medal9;
   int? medal10;

   int? medal11;
   int? medal12;
   int? medal13;
   int? medal14;
   int? medal15;

   int? medal16;
   int? medal17;
   int? medal18;
   int? medal19;
   int? medal20;

  //Default constructor
  Medal(this.id, this.medal1, this.medal2,this.medal3,this.medal4, this.medal5,this.medal6,this.medal7, this.medal8,this.medal9,this.medal10, this.medal11,this.medal12,
       this.medal13, this.medal14,this.medal15,this.medal16, this.medal17,this.medal18,this.medal19,this.medal20);  
}